### PR TITLE
remove brooklyn-client Godep from repo

### PR DESCRIPTION
**Pull request by johnmccabe**
@geomacy can you have a look at this, leaving this in results in mvn building from the old Godep. I can build via `mvn`, `godep install`

### CODE REVIEW

**Comment by geomacy** [comment]
:+1: looks good to me, I pulled this and confirm that it builds correctly

**Comment by robertgmoss** [comment]
I believe it is customary in Golang circles to commit the Godep to repos.  If the Godep is out of date perhaps it should be updated?

**Comment by johnmccabe** [comment]
@robertgmoss even for the repo itself? I can see the rationale behind committing dependencies (-ish) but by committing the repo you're either having to update files twice or each update requires 2 commits?

**Comment by robertgmoss** [comment]
Ah didn't see that! I thought you were removing everything.  Should be fine the way you have it.

**Comment by johnmccabe** [comment]
figured :) I was about to bust out my 'I heard you like repos so I put a repo in your repo' meme.

**Comment by robertgmoss** [comment]
I have a feeling the Godeps.json file has not been created properly - I think it is only supposed to have external dependencies in there...

**Comment by geomacy** [comment]
You're quite right @robertgmoss, it shouldn't have references to brooklyn-client itself in it.

**Comment by johnmccabe** [comment]
currently its the `godep save` thats adding brooklyn-client

**Comment by johnmccabe** [comment]
I suspect its due to godeps existing in the br subdirectory rather than in the root of the project

**Comment by johnmccabe** [comment]
gonna try reorging it here

**Comment by johnmccabe** [comment]
moving the src up into the br subdirectory should fix the godep behaviour (moving Godep down also fixes it but you then hit the problem that the repo name doesn't match the br binary).

as @geomacy points out given that there is an intention to move away from godep to the vendoring in 1.6 its probably not worth attempting to make further changes at this point.

this PR in its current form at least ensures the binary is built from the latest code rather than an obsolete copy of the repo, I suggest we commit this and can revisit vendoring as part of the 1.6 move.

**Comment by robertgmoss** [comment]
+1

**Comment by geomacy** [comment]
that sounds like a reasonable plan to me. I'd hope to get the 1.6 vendoring support added sooner rather than later, in time for a 0.9.0 release of Brooklyn.

**Comment by johnmccabe** [comment]
just had a look at the vendoring in 1.6 and it appears that you're going to hit the same problem with directory structuring

**Comment by neykov** [comment]
Are the changes mentioned by @johnmccabe done ("moving the src up into the br subdirectory should fix the godep behaviour")? Is this PR ready to merge?

**Comment by johnmccabe** [comment]
@neykov that change wasn't carried out at the time (see [comment](https://github.com/apache/brooklyn-client/pull/11#issuecomment-199831958), the PR as-is allows the client to build as expected pending the 1.6 vendoring support @geomacy plans to add - suggest we merge in its absence.

**Comment by neykov** [comment]
Thanks @johnmccabe, merging.

**Pull request merged**
