### PR TITLE
move rest-client to brooklyn-client

### PR DESCRIPTION
**Pull request by andreaturli**
See also https://github.com/apache/brooklyn-server/pull/325 , merge them in tandem, if ok.

### CODE REVIEW

**Comment by geomacy** [comment]
@andreaturli what's the reason for this?  I think it would be better to keep the `br` CLI as a separate, Go, project, and not add in unrelated code.  If there's some reason why the rest client needs to be moved away from brooklyn-server let's move it somewhere independent. I don't think the Go project is the right place for it.

**Comment by andreaturli** [comment]
@geomacy, I think `brooklyn-client` may be the home for multiple brooklyn clients. I think the `go cli` is just one (the preferred one!), `java` is another one, and ideally we could have rest clients for more languages. I guess I'm interpreting that project as `brooklyn-clients`, sounds wrong to you guys?

we could move the java rest client elsewhere, but is it worth?

**Comment by andreaturli** [comment]
As for the reason: `brooklyn-server` has a dependency on `resteasy` which is used only by the `rest/rest-client` module. Having `resteasy` and `cxf` (2 jax-rs implementations) in the classpath looks redundant, not considering the extra work needed to support osgi bundles for both. Notice also jaxrs implementation are not really osgi-friendly  (ask @googlielmo and @neykov for more details :P) so I think a diet for `brooklyn-server` is not a bad thing :)

**Comment by geomacy** [comment]
It just feels wrong to me from the "keep things decoupled" / "do one thing" viewpoint.    If I am a Go developer I might want to contribute to the brooklyn-client, but if I have no Java background as well I will be put off by all that Java.  Adding the REST client here mixes together two completely different technologies in one project.

**Comment by geomacy** [comment]
the `resteasy` issue is its own thing, we should fix that in brooklyn-server, or, if moving the code is the right solution, fair enough, but I don't think this is the right place to move it.

**Comment by andreaturli** [comment]
I see your good point, @geomacy 
Let's discuss it more broadly, then. I'll ask the mailing list, thanks!

**Comment by geomacy** [comment]
yes, definitely worth discussing there, thanks @andreaturli

**Comment by geomacy** [comment]
@andreaturli you'll need to update the README.md to reflect the new location of the Go code.

**Comment by ahgittin** [comment]
interesting discussion on mailing list but seems like consensus is to go with what you've originally done here @andreaturli 

merge away!

**Pull request merged**
