### PR TITLE
move CLI project from brooklyncentral

### PR DESCRIPTION
**Pull request by ahgittin**
from https://github.com/brooklyncentral/brooklyn-cli/

### CODE REVIEW

**Comment by ahgittin** [comment]
note you still have to set up your environment to build, and this isn't integrated with the uber-project build or the dist yet, but that means it is safe to merge without risk of breaking and at least the code will be living in the right place with this

**Comment by richardcloudsoft** [comment]
Please do not merge just yet. The size of this contribution would very likely require a code grant if we were still in the incubator, so I need to check what the equivalent procedure for a TLP is.

**Comment by geomacy** [comment]
hi @richardcloudsoft did you ever find out whether we can merge this now?   

It would be great to have this merged in order to work from to prepare an 0.9.0 release.

**Comment by rdowner** [comment]
Hi @geomacy. Sorry I dropped the ball on this. I think I know what the process is now and am seeking confirmation (see post on dev@brooklyn)

**Comment by geomacy** [comment]
Thanks @rdowner

**Comment by robertgmoss** [comment]
@ahgittin there are a couple of new commits to the other repo since this PR.

**Comment by rdowner** [comment]
@robertgmoss @ahgittin We're not frozen yet so feel free to add more commits to the PR. Once the vote completes we'll probably have to pick a commit as the basis for the Software Grant Agreement, but that will be Monday at the earliest and we can discuss it then.

**Comment by ahgittin** [comment]
**UPDATE 1 Mar**

* IP grants have been obtained; there is now a vote to accept this
* potential issues around embedded deps (BSD+MIT license) and apparent crypto dep (but it is actually just terminal support/emulation) have been investigated and found to be fine (see ML)
* LICENSE file still needs an update for the embedded deps, expected soon
* once the above is completed, including the vote, we believe this is ready to merge

**Comment by rdowner** [comment]
The vote passed so we have a green light to merge. See the [IP Clearance record](https://incubator.apache.org/ip-clearance/brooklyn-cli.html).

**Pull request merged**
